exclude: examples/.*/settings/derex/.*
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: .bumpversion.cfg
      - id: debug-statements
      - id: check-added-large-files
      - id: end-of-file-fixer
        exclude: .bumpversion.cfg
      - id: check-yaml
        exclude: docker_build/mongoid.yml

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.961
  #   hooks:
  #     - id: mypy
  #       exclude: docs/conf.py|examples
  #       args:
  #         ["--install-types", "--non-interactive", "--ignore-missing-imports"]

  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
